DROP TABLE IF EXISTS RETAIL_SALES; 


CREATE TABLE RETAIL_SALES (
transactions_id INT PRIMARY KEY,
sale_date	DATE,
sale_time   TIME,
customer_id   INT,
gender       VARCHAR(15),
age	          INT,
category      VARCHAR(20),
quantiy	      INT,
price_per_unit  FLOAT,
cogs	         FLOAT,
total_sale    FLOAT
);

SELECT * FROM RETAIL_SALES;
SELECT COUNT(*) FROM RETAIL_SALES;

ALTER TABLE RETAIL_SALES
RENAME COLUMN QUANTIY TO QUANTITY;

 -- DATA CLEANING
SELECT * FROM RETAIL_SALES WHERE 
QUANTITY IS NULL;


DELETE FROM RETAIL_SALES WHERE 
QUANTITY IS NULL
OR 
PRICE_PER_UNIT IS NULL
OR 
COGS IS NULL
OR 
TOTAL_SALE IS NULL;

-- DATA EXPLORATION
-- HOW MANY SALES DO WE HAVE 
SELECT COUNT(*) FROM RETAIL_SALES;

-- HOW MANY UNIQUE CUSTOMERS WE HAVE
SELECT COUNT(DISTINCT(CUSTOMER_ID)) FROM RETAIL_SALES;
SELECT DISTINCT CUSTOMER_ID FROM RETAIL_SALES;

-- HOW MANY CATEGORIES WE HAVE
SELECT COUNT(DISTINCT(CATEGORY)) FROM RETAIL_SALES;
SELECT DISTINCT CATEGORY FROM RETAIL_SALES;

-- SOLVING BUSINESS PROBLEMS

--Q1. WRITE A SQL QUERY TO RETRIEVE SALES DONE ON 2022/11/05
SELECT * FROM RETAIL_SALES WHERE SALE_DATE = '2022-11-05';

--Q2. WRITE A SQL QUERY TO RETRIEVE SALES FROM CLOTHING CATEGORY,QUANTITY IS MORE THAN 4, AND SALES 
-- HAPPENED ON NOV 2022
SELECT *
FROM retail_sales
WHERE lower(category) = 'clothing'
AND quantity >= 4
AND TO_CHAR(sale_date, 'YYYY-MM') = '2022-11';

--Q3. WRITE A SQL QUERY TO CALCULATE TOTAL SALES BASED ON EACH CATEGORY
SELECT CATEGORY , SUM(TOTAL_SALE),COUNT(*) FROM retail_sales
GROUP BY CATEGORY;

--Q4. WRITE A SQL QUERY TO RETRIEVE AVERAGE AGE OF CUSTOMERS FROM BEAUTY CATEGORY
SELECT (AVG(age) FROM retail_sales WHERE lower(CATEGORY) = 'beauty';
SELECT ROUND((AVG(age), 2) FROM retail_sales WHERE lower(CATEGORY) = 'beauty';
SELECT  distinct age FROM retail_sales WHERE lower(category) = 'beauty';

--Q5. WRITE A SQL QUERY TO RETRIEVE ALL TRANSACTIONS WHERE TOTAL_SALE IS MORE THAN 1000
SELECT * FROM retail_sales WHERE total_sale > 1000;

--Q6. WRITE A SQL QUERY TO FIND TOTAL TRANSACTIONS MADE BY EACH GENDER IN EACH CATEGORY
SELECT CATEGORY , GENDER, COUNT(*) FROM retail_sales 
GROUP BY CATEGORY , GENDER
order by 1;

--*Q7. WRITE A SQL QUERY TO CALCULATE AVERAGE SALE FOR EACH MONTH AND FIND OUT BEST SELLING MONTH OF EACH YEAR 
SELECT * FROM (
SELECT 
EXTRACT(YEAR FROM sale_date) as year,
EXTRACT(MONTH FROM sale_date) as month,
avg(total_sale),
RANK() OVER(PARTITION BY EXTRACT(YEAR FROM sale_date) ORDER BY avg(total_sale)DESC)
as Rank
FROM retail_sales
GROUP BY year, month)
AS t1 WHERE Rank = 1;

SELECT * FROM retail_sales;

-- Q8. WRITE A SQL QUERY TO FIND TOP 10 CUSTOMERS BASED ON HIGHEST TOTAL_SALES
SELECT customer_id, SUM(total_sale)
FROM retail_sales GROUP BY customer_id
ORDER BY 2 DESC
LIMIT 10;

-- Q9. WRITE A SQL QUERY TO FIND NUMBER OF UNIQUE CUSTOMERS FROM EACH CATEGORY
SELECT category, COUNT(DISTINCT customer_id) as unique_customers
FROM retail_sales
GROUP BY 1;

--Q10.WRITE A SQL QUERY TO FIND EACH SHIFT AND NUMBER OF ORDERS IN EACH SHIFT
-- EXAMPLE(UPTO 12AM MORNING SHIFT, 12-17 AFTERNOON , ELSE EVENING)
WITH hourly_sales 
AS (
SELECT *,
CASE 
    WHEN EXTRACT(HOUR from sale_time) < 12 THEN 'Morning'
	WHEN EXTRACT(HOUR from sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
	ELSE 'Evening'
	END as shift
FROM retail_sales
) 
SELECT shift,
COUNT(*) as total_sales
FROM hourly_sales 
GROUP BY shift;

-- END OF PROJECT





	



















